### ISSUE TITLE
Processing Modules in TBB

### ISSUE THREAD

**Issue by huston8** [sdl/dxa-content-management#2]
Hi,

While going through the TBBs for DXA implementation, I noticed a method `GetModuleNameFromConfig` in `TemplateBase.cs` file used to fetch the module name. 
The implementation is like:

    protected string GetModuleNameFromConfig(Component configComponent)
    {
      //Module config components are always found in /Modules/{Name}/System/, so the module name is defined to be the name of the folder 2 levels up.
      return configComponent.OrganizationalItem.OrganizationalItem.Title.ToLower();
    }

This method gets the module name from the folder name and will fail if folder hierarchy is changed due to some reason. 
There is a field for module name in `Module Configuration` Schema which can be used instead.

The method for this can be like:

    protected string GetModuleNameFromConfigComponent(Component configComponent)
    {
      var fields = new ItemFields(configComponent.Content, configComponent.Schema);
      return fields.GetTextValue("name").ToLower();
    }

This method does not have any dependency on folder structure.

Kindly let me know if this is correct?

**Comment by jhorsman** [comment]
Good find. And I think this is a good improvement.

Some comments:
- The code comment "//Module config components are always found in /Modules/{Name}/System/ ..." is wrong. The config components are found in /some folder/{Name}/***Admin***/.
- Other than this TBB nothing is stopping you from putting a module in a different folder which is not a child of `/Building Blocks/Modules`. You can for example nest modules like `/Building Blocks/My Custom Modules/CustomSearch`.
- The GetModuleNameFromConfig() method is not working for you because the module name in the configuration component is not the same as the module folder name. The fact that your module is nested and not in `/Building Blocks/Modules` is unrelated.
- Please indent code bocks in GitHub issues with backticks or 4 spaces  https://guides.github.com/features/mastering-markdown/

**Comment by huston8** [comment]
Thanks @jhorsman for the suggests. Updated the post. :+1: 

- The code comment "//Module config components are always found in /Modules/{Name}/System/ ..." is wrong. The config components are found in /some folder/{Name}/Admin/.

 This comment was present in original TBB itself :)

- The GetModuleNameFromConfig() method is not working for you because the module name in the configuration component is not the same as the module folder name. The fact that your module is nested and not in /Building Blocks/Modules is unrelated.

I did not get this completely ....But module name is read from Grandparent folder instead of the field in component.

**Comment by jhorsman** [comment]
> I did not get this completely ....But module name is read from Grandparent folder instead of the field in component.
Indeed, so a workaround is to align the folder name and the name field in the module configuration component.

**Comment by jhorsman** [comment]
This issue was first reported on Tridion.Stackexchange in July 2015. See http://tridion.stackexchange.com/questions/12331/how-to-use-the-core-and-html-design-configuration-components-in-dxa#comment15436_12339

**Comment by rpannekoek** [comment]
Incorporated in DXA 1.4.
