### ISSUE TITLE
Multi-value field enhancement

### ISSUE THREAD

**Issue by Vouzamo** [sdl/dxa-content-management#28]
See: https://github.com/sdl/dxa-model-service/issues/6

I propose the serialization uses the schema to properly serialize multi-value fields as array regardless of how many values are populated if the corresponding schema field is multi-value.

**Comment by rpannekoek** [comment]
As I commented on the reference issue too: the DXA TBBs don't use CM Schemas for the XML->JSON transformation for performance reasons.
For this purpose, the DXA R2 Data Model has intentionally loosely typed content/metadata model.
The DXA R2 Data Model is intended to be used as input for the DXA Semantic Mapping (which has access to CM Schema data out-of-band);  the DXA R2 Data Model is not intended for direct consumption in Web Applications.

**Comment by Vouzamo** [comment]
This seems a weak excuse since there is no notable performance hit from loading a schema and almost all other TBBs will use Tom.NET to load a schema. How can you represent a content model when disregarding the contract it should observe?

**Comment by rpannekoek** [comment]
We have seen performance issues with DD4T TBBs where a significant performance overhead was caused by the use of TOM.NET ItemFields (which results in loading/compiling of CM Schemas).  Being able to get rid of this significant performance overhead was one of the reasons for introducing the R2 Data Model (and associated CM-side model builder pipeline).
Again, the DXA Semantic Mapping has all the Schema information anyways, so doesn't need a more strongly typed Data Model.

**Comment by Vouzamo** [comment]
Okay. Thanks for confirming. I will drop support for DXA and roll my own serializer instead.
